from __future__ import annotations

import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[2]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.chat.ws_contract import export_chat_ws_contract_manifest, validate_chat_ws_manifest


def _camel_case(value: str) -> str:
    head, *tail = value.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in tail)


def _render_const_object(name: str, value: dict[str, str]) -> str:
    lines = [f"export const {name} = {{"]
    for key, item in value.items():
        lines.append(f'  {_camel_case(key)}: "{item}",')
    lines.append("} as const;")
    return "\n".join(lines)


def _render_const_array(name: str, value: list[str]) -> str:
    items = ", ".join(f'"{item}"' for item in value)
    return f"export const {name} = [{items}] as const;"


def _render_typescript(manifest: dict[str, object]) -> str:
    channels = manifest["channels"]
    methods = manifest["methods"]
    stream_event_types = manifest["stream_event_types"]
    user_event_types = manifest["user_event_types"]
    tool_names = manifest["tool_names"]
    interactive_tool_names = manifest["interactive_tool_names"]

    return """// Generated by backend/scripts/contracts/export_chat_ws_contract.py
// Do not edit by hand.

{channels}
export type ChatWsChannel = (typeof CHAT_WS_CHANNELS)[keyof typeof CHAT_WS_CHANNELS];

{methods}
export type ChatWsMethod = (typeof CHAT_WS_METHODS)[keyof typeof CHAT_WS_METHODS];

{stream_event_types}
export type ChatStreamEventType = (typeof CHAT_STREAM_EVENT_TYPES)[number];
const CHAT_STREAM_EVENT_TYPE_SET = new Set<string>(CHAT_STREAM_EVENT_TYPES);
export function isChatStreamEventType(value: unknown): value is ChatStreamEventType {{
  return typeof value === "string" && CHAT_STREAM_EVENT_TYPE_SET.has(value);
}}

{user_event_types}
export type ChatUserEventType = (typeof CHAT_USER_EVENT_TYPES)[number];
const CHAT_USER_EVENT_TYPE_SET = new Set<string>(CHAT_USER_EVENT_TYPES);
export function isChatUserEventType(value: unknown): value is ChatUserEventType {{
  return typeof value === "string" && CHAT_USER_EVENT_TYPE_SET.has(value);
}}

{tool_names}
export type ChatToolName = (typeof CHAT_TOOL_NAMES)[number];
const CHAT_TOOL_NAME_SET = new Set<string>(CHAT_TOOL_NAMES);
export function isChatToolName(value: unknown): value is ChatToolName {{
  return typeof value === "string" && CHAT_TOOL_NAME_SET.has(value);
}}

{interactive_tool_names}
export type ChatInteractiveToolName = (typeof CHAT_INTERACTIVE_TOOL_NAMES)[number];
const CHAT_INTERACTIVE_TOOL_NAME_SET = new Set<string>(CHAT_INTERACTIVE_TOOL_NAMES);
export function isChatInteractiveToolName(value: unknown): value is ChatInteractiveToolName {{
  return typeof value === "string" && CHAT_INTERACTIVE_TOOL_NAME_SET.has(value);
}}

export type ChatUserActiveStream = {{
  conversation_id: string;
  user_message_id?: string | null;
  run_id?: string | null;
  started_at?: string | null;
  current_step?: string | null;
}};

export type ChatInitialStateUserEvent = {{
  type: "initial_state";
  streams?: ChatUserActiveStream[];
}};

export type ChatRunLifecycleUserEvent = {{
  type: Extract<ChatUserEventType, "stream_started" | "stream_resumed" | "stream_paused" | "stream_completed" | "stream_failed">;
  conversation_id: string;
  user_message_id?: string | null;
  run_id?: string | null;
  status?: string | null;
  current_step?: string | null;
  started_at?: string | null;
}};

export type ChatConversationTitleUpdatedUserEvent = {{
  type: "conversation_title_updated";
  conversation_id: string;
  title: string;
  updated_at?: string | null;
  source?: string | null;
}};

export type ChatUserEvent =
  | ChatInitialStateUserEvent
  | ChatRunLifecycleUserEvent
  | ChatConversationTitleUpdatedUserEvent;

export type ChatWsPingBody = {{
  _tag: typeof CHAT_WS_METHODS.ping;
}};

export type ChatWsConversationBody = {{
  conversationId: string;
}};

export type ChatWsSubscribeStreamBody = ChatWsConversationBody & {{
  _tag: typeof CHAT_WS_METHODS.subscribeStream;
  sinceStreamEventId?: number;
  runMessageId?: string | null;
}};

export type ChatWsUnsubscribeStreamBody = ChatWsConversationBody & {{
  _tag: typeof CHAT_WS_METHODS.unsubscribeStream;
}};

export type ChatWsCancelStreamBody = ChatWsConversationBody & {{
  _tag: typeof CHAT_WS_METHODS.cancelStream;
}};

export type ChatWsRequestBody =
  | ChatWsPingBody
  | ChatWsSubscribeStreamBody
  | ChatWsUnsubscribeStreamBody
  | ChatWsCancelStreamBody;

export type ChatWsRequestEnvelope = {{
  id: string;
  body: ChatWsRequestBody;
}};

export type ChatWsResponseEnvelope = {{
  id: string;
  result?: unknown;
  error?: {{
    message?: unknown;
  }};
}};

export type ChatWsUserEventPushData = ChatUserEvent;

export type ChatWsStreamPushData = {{
  conversationId: string;
  event: {{
    id: number;
    type: ChatStreamEventType;
    data?: unknown;
  }};
}};

export type ChatWsPushEnvelope =
  | {{
      type: "push";
      channel: typeof CHAT_WS_CHANNELS.userEvent;
      data: ChatWsUserEventPushData;
    }}
  | {{
      type: "push";
      channel: typeof CHAT_WS_CHANNELS.streamEvent;
      data: ChatWsStreamPushData;
    }};
""".format(
        channels=_render_const_object("CHAT_WS_CHANNELS", channels),
        methods=_render_const_object("CHAT_WS_METHODS", methods),
        stream_event_types=_render_const_array("CHAT_STREAM_EVENT_TYPES", stream_event_types),
        user_event_types=_render_const_array("CHAT_USER_EVENT_TYPES", user_event_types),
        tool_names=_render_const_array("CHAT_TOOL_NAMES", tool_names),
        interactive_tool_names=_render_const_array(
            "CHAT_INTERACTIVE_TOOL_NAMES", interactive_tool_names
        ),
    )


def main() -> int:
    if len(sys.argv) != 2:
        print(
            "Usage: PYTHONPATH=. python scripts/contracts/export_chat_ws_contract.py <output-path>"
        )
        return 1

    validate_chat_ws_manifest()
    output_path = Path(sys.argv[1]).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    manifest = export_chat_ws_contract_manifest()
    output_path.write_text(_render_typescript(manifest), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
